// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3v5jbvLdFCXWaSlv22A4JGlgJ6DUGDyA',
    appId: '1:775838316564:web:7a1dc6a967d53734394f01',
    messagingSenderId: '775838316564',
    projectId: 'game-haven-2608d',
    authDomain: 'game-haven-2608d.firebaseapp.com',
    storageBucket: 'game-haven-2608d.firebasestorage.app',
    measurementId: 'G-ZRZHPXQZ7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSaeAO3aD9sl7vvKpygnmlt1tIe6sN_w',
    appId: '1:775838316564:android:867247405bfbd4ed394f01',
    messagingSenderId: '775838316564',
    projectId: 'game-haven-2608d',
    storageBucket: 'game-haven-2608d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyswDAYQ1vUPR1rsnxdWX6yCZeFv1tW2Q',
    appId: '1:775838316564:ios:761a9a8ecdacc10b394f01',
    messagingSenderId: '775838316564',
    projectId: 'game-haven-2608d',
    storageBucket: 'game-haven-2608d.firebasestorage.app',
    iosBundleId: 'com.example.gameHaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyswDAYQ1vUPR1rsnxdWX6yCZeFv1tW2Q',
    appId: '1:775838316564:ios:761a9a8ecdacc10b394f01',
    messagingSenderId: '775838316564',
    projectId: 'game-haven-2608d',
    storageBucket: 'game-haven-2608d.firebasestorage.app',
    iosBundleId: 'com.example.gameHaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3v5jbvLdFCXWaSlv22A4JGlgJ6DUGDyA',
    appId: '1:775838316564:web:985358053e0e7644394f01',
    messagingSenderId: '775838316564',
    projectId: 'game-haven-2608d',
    authDomain: 'game-haven-2608d.firebaseapp.com',
    storageBucket: 'game-haven-2608d.firebasestorage.app',
    measurementId: 'G-14T15FGRZC',
  );
}
