default_platform(:android)

platform :android do
  desc "Build and distribute to Firebase"
  lane :distribute do
    sh("flutter build apk --release")

    firebase_app_distribution(
      app: "1:471308320747:android:bd5aa651463741893e63ae", 
      groups: "testers",
      release_notes: "Second automated build from Fastlane!",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      timeout: 600,
    )
  end
end